### ISSUE TITLE
Potential error point

### ISSUE THREAD

**Issue by sanders41** [ikollipara/django-meili#1]
This code could potentially error. The reason is `create_index` is asyncronous in Meilisearch so if your code tries to update the settings before the index gets created it will error. You are unlikely to see this in development because there won't be many tasks and therefore the index should get created quickly. 

One solution would be to wait for the index creation to complete. The thing to be aware of here is the program will be blocked while it waits. Most of the time this will be fast and not noticable, but it's something to be aware of. If you want me to do a PR to add this let me know and I can.

If you decide to leave things as they are it will be a race condition kind of bug. It will most likely be rare that you see it, so just be aware that if you see an error here that you can't explain or easily reproduce this could be the issue.

https://github.com/ikollipara/django-meili/blob/5319ae2dd6ed40c2c0c391e71e18ab75e6c1f8e2/src/django_meili/models.py#L43-L57

**Comment by sanders41** [comment]
It is possible that Meilisearch is still processing the index creation when it gets to the `update_displayed_attributes`. If this happens the index won't be created yet and it will error.

**Comment by ikollipara** [comment]
According to their docs:

After creating a task, Meilisearch places it in a queue. Enqueued tasks are processed one at a time, following the order in which they were requested. [(Source)](https://www.meilisearch.com/docs/learn/async/asynchronous_operations)

So if they're processed one at a time, this shouldn't be an issue.

**Comment by sanders41** [comment]
Like I said it's fine to leave it as is. I can just tell you I have seen errors from this before.

**Comment by ikollipara** [comment]
Sure, I'm not disagreeing with you. Do you think adding an additional setting to wait for that task completion, or just have that as default would be better?

**Comment by sanders41** [comment]
Another idea...maybe catch the error if the index doesn't exist and do the wait there and retry. Then you only need to wait if you get an error that the index doesn't exist.

**Comment by ikollipara** [comment]
I like that idea. I'll play around with it for a bit and see what I can do. Thank you for your input, it really helps!
