### ISSUE TITLE
MeilisearchCommunication Error SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by eznix86** [ikollipara/django-meili#3]
Description
I use a dockerized version of meilisearch. When using the hostname to connect, it fails.

Expected behavior
Supposed to connect.

Current behavior
Getting an SSL WRONG VERSION

Screenshots or Logs
```sh
File "/opt/.venv/lib/python3.12/site-packages/meilisearch/_httprequests.py", line 64, in send_request
raise MeilisearchCommunicationError(str(err)) from err
meilisearch.errors.MeilisearchCommunicationError: MeilisearchCommunicationError, HTTPSConnectionPool(host='meilisearch', port=7700): Max retries exceeded with url: /indexes (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))
```
Environment (please complete the following information):

    OS: Docker, python:3.12-bookworm
    Meilisearch version: v1.7.6
    meilisearch-python version: 0.31.0

**Comment by ikollipara** [comment]
Can I see your configuration for connecting to meilisearch? My guess is that it doesn't resolve the custom hostname on the network.

**Comment by ikollipara** [comment]
I would google the meilisearch SSL version it expects and make sure that's installed. If you're using Mac its easy enough to install through Brew. I'm not sure on windows.
