### ISSUE TITLE
Superfluous network call in `Client.create_index()`

### ISSUE THREAD

**Issue by soulshake** [ikollipara/django-meili#7]
(This is a very minor issue noticed while investigating #6 :) )

https://github.com/ikollipara/django-meili/blob/7c908da11c9e96a098ad5415274ce0202572caeb/django_meili/_client.py#L35-L47

The result of `self.indexes()` is a list of `meilisearch.index.Index`:

```
In [3]: self.get_indexes()
2024-06-25 09:59:38 [connectionpool.py:1021] urllib3.connectionpool DEBUG Starting new HTTPS connection (1): search.example.com:443
2024-06-25 09:59:38 [connectionpool.py:474] urllib3.connectionpool DEBUG https://search.ephemerasearch.com:443 "GET /indexes HTTP/1.1" 200 None
Out[3]: 
[<meilisearch.index.Index at 0x7fdf3839c110>,
 <meilisearch.index.Index at 0x7fdf3839c210>,
 <meilisearch.index.Index at 0x7fdf3839c350>,
 <meilisearch.index.Index at 0x7fdf3839c4d0>,
 <meilisearch.index.Index at 0x7fdf3839c650>,
 <meilisearch.index.Index at 0x7fdf3839c810>,
 <meilisearch.index.Index at 0x7fdf3839c990>]
```

...whereas `index_name` is a string, so if I'm not mistaken, this line will never be True:

https://github.com/ikollipara/django-meili/blob/7c908da11c9e96a098ad5415274ce0202572caeb/django_meili/_client.py#L45

**Comment by ikollipara** [comment]
Thanks for the catch, I hadn't realized that. I've updated the code to check against the gathered indexes uids (which are strings). Thanks!
